name: Auto Version Tag & Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all history is fetched for tag retrieval

      - name: Get latest commit message
        id: commit_message
        run: echo "COMMIT_MSG=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git tag --sort=-v:refname | head -n 1)

          if [[ -z "$latest_tag" ]]; then
            new_tag="v1.0.0"
          else
            major=$(echo $latest_tag | cut -d. -f1 | tr -d 'v')
            minor=$(echo $latest_tag | cut -d. -f2)
            patch=$(echo $latest_tag | cut -d. -f3)

            if [[ "${{ env.COMMIT_MSG }}" == *"feat:"* ]]; then
              new_tag="v$major.$((minor + 1)).0"
            else
              new_tag="v$major.$minor.$((patch + 1))"
            fi
          fi

          echo "NEW_TAG=$new_tag" >> $GITHUB_ENV
          echo "New tag: $new_tag"

      - name: Create Git Tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/flask-app"

          docker build -t $IMAGE_NAME:$NEW_TAG .
          docker tag $IMAGE_NAME:$NEW_TAG $IMAGE_NAME:latest

      - name: Push Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/flask-app"

          docker push $IMAGE_NAME:$NEW_TAG
          docker push $IMAGE_NAME:latest
