name: Generate Docker Image

on:
  push:
    branches:
      - main  # Run only on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Determine version bump
        id: get_version
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          VERSION_MAJOR=$(echo $LAST_TAG | cut -d. -f1)
          VERSION_MINOR=$(echo $LAST_TAG | cut -d. -f2)
          VERSION_PATCH=$(echo $LAST_TAG | cut -d. -f3)

          COMMIT_MSG=$(git log -1 --pretty=%B)

          if echo "$COMMIT_MSG" | grep -qE "^upgrade:"; then
            VERSION_MAJOR=$((VERSION_MAJOR + 1))
            VERSION_MINOR=0
            VERSION_PATCH=0
          elif echo "$COMMIT_MSG" | grep -qE "^feat:"; then
            VERSION_MINOR=$((VERSION_MINOR + 1))
            VERSION_PATCH=0
          else
            VERSION_PATCH=$((VERSION_PATCH + 1))
          fi

          NEW_TAG="$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myflaskapp:${{ env.NEW_TAG }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/myflaskapp:${{ env.NEW_TAG }}

      - name: Configure Git and Push Tag
        run: |
          git config --global user.name "rohitpatil07"
          git config --global user.email "rohitpatil07122001@gmail.com"
          git remote set-url origin https://github.com/rohitpatil07/myflaskapp.git
          echo "https://rohitpatil07:${{ secrets.PAT_GITHUB }}" > ~/.git-credentials
          git config --global credential.helper store
          git tag ${{ env.NEW_TAG }}
          git push https://rohitpatil07:${{ secrets.PAT_GITHUB }}@github.com/rohitpatil07/myflaskapp.git ${{ env.NEW_TAG }}
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
